namespace: argocd-control-prod

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/andrewtyped/argocd.control.git
    targetRevision: refs/tags/prod
    helm:
      valueFiles:
        - values.dev.yaml
        - values.dev.automation.yaml