apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ping
  name: ping
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: ping
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ping
    spec:
      containers:
      #us-east1-docker.pkg.dev/virtual-transit-432200-s6/docker-repo/dotnet-ping:20240831.9
      - image: {{ .Values.Image }}
        name: ping
        ports:
        - containerPort: 80
        - containerPort: 443