apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-control
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Demo Argo CD Project
  sourceRepos: 
    - 'https://github.com/andrewtyped/argocd.control.git'
  destinations:
    - namespace: argocd-control*
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true