apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ping-{{ .Values.namespace }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    namespace: {{ .Values.namespace }}
    server: {{.Values.spec.destination.server}}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: ./src/ping/
    helm:
      valueFiles:
{{ toYaml .Values.spec.source.helm.valueFiles | indent 8}}