apiVersion: v1
kind: Service
metadata:
  name: pong-service
spec:
  selector:
    app.kubernetes.io/name: pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 192.0.2.127